apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: instapay-dev
  labels:
    app: frontend
    environment: dev
spec:
  selector:
    app: frontend
    environment: dev
  ports:
    - port: 80
      targetPort: 5173
  type: ClusterIP