apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instapay-ingress
  namespace: instapay-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - dev.instapay.com
    secretName: instapay-dev-tls
  rules:
  - host: dev.instapay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3001
      - path: /api/transactions
        pathType: Prefix
        backend:
          service:
            name: transaction-service
            port:
              number: 3002
      - path: /api/reports
        pathType: Prefix
        backend:
          service:
            name: reporting-service
            port:
              number: 3003 