apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:

  POSTGRES_ADMIN_USER:     admin
  POSTGRES_ADMIN_PASSWORD: admin
  
  DB_PASSWORD:             Destiny2
  JWT_SECRET:              OH_ANA_ESMY_SANO
