apiVersion: batch/v1
kind: Job
metadata:
  name: transaction-service-migration
  namespace: instapay-dev
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: instapay/transaction-service:dev
        command: ["npx", "sequelize-cli", "db:migrate", "--env", "dev", "--config", "/app/config/config.js"]
        envFrom:
        - configMapRef:
            name: transaction-service-configmap
        - secretRef:
            name: postgres-secret
      restartPolicy: Never
  backoffLimit: 2