apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: instapay-dev
data:
  DB_USER: admin
  DB_HOST: postgres
  DB_NAME_USER_SERVICE: user-service-dev
  NODE_ENV: dev
  USER_SERVICE_URL: http://user-service:3001
  TRANSACTION_SERVICE_URL: http://reporting-service:3003
