apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  # from .env.dev
  DB_USER:                   postgres
  DB_HOST:                   postgres
  DB_NAME_USER_SERVICE:      user-service-dev
  NODE_ENV:                  dev
