apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: instapay-dev
data:
  DB_USER:                   admin
  DB_HOST:                   postgres
  DB_PORT:                   "5432"
  DB_NAME_USER_SERVICE:      user-service-dev
  ENV:                       dev
  TRANSACTION_SERVICE_URL: http://transaction-service:3002
  REPORTING_SERVICE_URL: http://reporting-service:3003
  USER_SERVICE_URL: http://user-service:3001
