apiVersion: batch/v1
kind: Job
metadata:
  name: transaction-service-migration
  namespace: instapay-prod

spec:
  template:
    spec:
      containers:
        - name: migrate
          image: instapay/transaction-service:prod
          command:
            [
              "npx",
              "sequelize-cli",
              "db:migrate",
              "--env",
              "prod",
              "--config",
              "/app/config/config.js",
            ]
          envFrom:
            - configMapRef:
                name: transaction-service-config
            - secretRef:
                name: postgres-secret
      restartPolicy: Never
  backoffLimit: 2
