apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_USER:                   admin
  DB_HOST:                   postgres
  DB_NAME_USER_SERVICE:      user-service-prod
  ENV:                       prod
