apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: instapay-prod
  labels:
    app: user-service
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
      environment: prod
  template:
    metadata:
      labels:
        app: user-service
        environment: prod
    spec:
      containers:
      - name: user-service
        image: instapay/user-service:prod
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: postgres-secret
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_ADMIN_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: JWT_SECRET
          - name: NODE_ENV
            value: "prod"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20