apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: instapay-staging
  labels:
    app: transaction-service
    environment: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
      environment: staging
  template:
    metadata:
      labels:
        app: transaction-service
        environment: staging
    spec:
      containers:
      - name: transaction-service
        image: instapay/transaction-service:staging
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: transaction-service-config
        - secretRef:
            name: postgres-secret
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_ADMIN_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_PASSWORD
          - name: ENV
            value: "staging"
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20