apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-migration
  namespace: instapay-staging

spec:
  template:
    spec:
      containers:
        - name: migrate
          image: instapay/user-service:staging
          command:
            [
              "npx",
              "sequelize-cli",
              "db:migrate",
              "--env",
              "staging",
              "--config",
              "/app/config/config.js",
            ]
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: postgres-secret
      restartPolicy: Never
  backoffLimit: 2
